type Query {
  audits(limit: Int, offset: Int,suc: Boolean): [Audit]
}

type Audit {
  id: String
  action: String
  suc: Boolean
  time: String
  uid: ID
  username: String
  password: String
  ip: String
  ipfs: [String]
}
